sonar.projectKey=grafana
sonar.projectName=Grafana Analytics App
sonar.projectVersion=1.0

# Path ke source code (kecualikan folder tests)
sonar.sources=internal,main.go

# Path ke lokasi file test
sonar.tests=tests

# File tempat menjabarkan hasil coverage hasil `go test -coverprofile`
sonar.go.coverage.reportPaths=coverage.out

# Pengecualian tambahan supaya seeder, file _test, DB config, dan main.go tidak di-scan sebagai logic production
sonar.exclusions=**/*_test.go,internal/seeder/**,main.go,internal/database/**
