package service_test

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/user/grafana-analytics-app/internal/models"
	"github.com/user/grafana-analytics-app/internal/service"
)

// MockOrderRepo is an autogenerated mock type for the OrderRepository type
type MockOrderRepo struct {
	mock.Mock
}

func (m *MockOrderRepo) InsertOrder(order *models.Order) error {
	args := m.Called(order)
	// mock assigns IDs
	if args.Error(0) == nil {
		order.ID = 1
	}
	return args.Error(0)
}

func (m *MockOrderRepo) GetTotalRevenueByStatus(status string) (float64, error) {
	args := m.Called(status)
	return args.Get(0).(float64), args.Error(1)
}

func TestProcessOrder_Success(t *testing.T) {
	mockRepo := new(MockOrderRepo)
	svc := service.NewOrderService(mockRepo)

	// Expectation
	mockRepo.On("InsertOrder", mock.AnythingOfType("*models.Order")).Return(nil)

	req := service.ProcessOrderRequest{
		CustomerID:    10,
		StoreID:       1,
		StaffReferral: 2,
		Amount:        100.0,
		Status:        "PAID",
	}

	order, err := svc.ProcessOrder(req)

	assert.NoError(t, err)
	assert.NotNil(t, order)
	assert.InDelta(t, 100.0, order.SubTotal, 0.001)
	assert.InDelta(t, 10.0, order.TaxAmount, 0.001)
	assert.InDelta(t, 110.0, order.FinalPrice, 0.001)
	assert.Equal(t, "PAID", order.Status)
	assert.Equal(t, uint(1), order.ID)

	mockRepo.AssertExpectations(t)
}

func TestProcessOrder_InvalidInput(t *testing.T) {
	mockRepo := new(MockOrderRepo)
	svc := service.NewOrderService(mockRepo)

	tests := []struct {
		name        string
		req         service.ProcessOrderRequest
		expectedErr string
	}{
		{
			name:        "Missing Customer ID",
			req:         service.ProcessOrderRequest{StoreID: 1, Amount: 100.0},
			expectedErr: "invalid customer or store ID",
		},
		{
			name:        "Missing Store ID",
			req:         service.ProcessOrderRequest{CustomerID: 1, Amount: 100.0},
			expectedErr: "invalid customer or store ID",
		},
		{
			name:        "Invalid Amount",
			req:         service.ProcessOrderRequest{CustomerID: 1, StoreID: 1, Amount: -10.0},
			expectedErr: "invalid order amount",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			order, err := svc.ProcessOrder(tt.req)
			assert.Error(t, err)
			assert.Nil(t, order)
			assert.Equal(t, tt.expectedErr, err.Error())
		})
	}
}

func TestProcessOrder_DefaultStatus(t *testing.T) {
	mockRepo := new(MockOrderRepo)
	svc := service.NewOrderService(mockRepo)

	mockRepo.On("InsertOrder", mock.AnythingOfType("*models.Order")).Return(nil)

	req := service.ProcessOrderRequest{
		CustomerID: 10,
		StoreID:    1,
		Amount:     100.0,
		// No Status provided
	}

	order, err := svc.ProcessOrder(req)

	assert.NoError(t, err)
	assert.Equal(t, "PAID", order.Status, "Should default to PAID status")
	mockRepo.AssertExpectations(t)
}

func TestProcessOrder_RepoError(t *testing.T) {
	mockRepo := new(MockOrderRepo)
	svc := service.NewOrderService(mockRepo)

	expectedErr := errors.New("database connection failed")
	mockRepo.On("InsertOrder", mock.Anything).Return(expectedErr)

	req := service.ProcessOrderRequest{
		CustomerID: 10,
		StoreID:    1,
		Amount:     100.0,
	}

	order, err := svc.ProcessOrder(req)

	assert.Error(t, err)
	assert.Nil(t, order)
	assert.Equal(t, expectedErr, err)
	mockRepo.AssertExpectations(t)
}

func TestCalculateTotalRevenue(t *testing.T) {
	mockRepo := new(MockOrderRepo)
	svc := service.NewOrderService(mockRepo)

	mockRepo.On("GetTotalRevenueByStatus", "PAID").Return(1500.0, nil)

	total, err := svc.CalculateTotalRevenue()
	assert.NoError(t, err)
	assert.Equal(t, 1500.0, total)
	mockRepo.AssertExpectations(t)
}

func TestCalculateTotalRevenue_Error(t *testing.T) {
	mockRepo := new(MockOrderRepo)
	svc := service.NewOrderService(mockRepo)

	mockRepo.On("GetTotalRevenueByStatus", "PAID").Return(0.0, errors.New("query err"))

	total, err := svc.CalculateTotalRevenue()
	assert.Error(t, err)
	assert.Equal(t, 0.0, total)
	assert.Equal(t, "query err", err.Error())
	mockRepo.AssertExpectations(t)
}
