package handler_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/user/grafana-analytics-app/internal/handler"
	"github.com/user/grafana-analytics-app/internal/models"
	"github.com/user/grafana-analytics-app/internal/service"
)

// MockOrderService is an autogenerated mock type for the OrderService type
type MockOrderService struct {
	mock.Mock
}

func (m *MockOrderService) ProcessOrder(req service.ProcessOrderRequest) (*models.Order, error) {
	args := m.Called(req)
	var order *models.Order
	if args.Get(0) != nil {
		order = args.Get(0).(*models.Order)
	}
	return order, args.Error(1)
}

func (m *MockOrderService) CalculateTotalRevenue() (float64, error) {
	args := m.Called()
	return args.Get(0).(float64), args.Error(1)
}

func setupRouter(mockSvc *MockOrderService) *gin.Engine {
	// Create prometheus mock components
	ordersProcessed := prometheus.NewCounter(prometheus.CounterOpts{
		Name: "test_retail_orders_processed_total",
	})
	totalRevenue := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "test_retail_revenue_total",
	}, []string{"country"})

	orderHandler := handler.NewOrderHandler(mockSvc, ordersProcessed, totalRevenue)

	gin.SetMode(gin.TestMode)
	router := gin.Default()
	router.POST("/api/orders", orderHandler.HandleProcessOrder)
	return router
}

func TestHandleProcessOrder_Success(t *testing.T) {
	mockSvc := new(MockOrderService)
	router := setupRouter(mockSvc)

	reqPayload := service.ProcessOrderRequest{
		CustomerID:    1,
		StoreID:       2,
		StaffReferral: 3,
		Amount:        100.0,
		Status:        "PAID",
	}
	body, _ := json.Marshal(reqPayload)

	expectedOrder := &models.Order{
		ID:         10,
		CustomerID: reqPayload.CustomerID,
		FinalPrice: 110.0,
	}

	mockSvc.On("ProcessOrder", reqPayload).Return(expectedOrder, nil)

	req, _ := http.NewRequest(http.MethodPost, "/api/orders", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")

	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusCreated, w.Code)
	
	// Unmarshal and verify response
	var response map[string]interface{}
	err := json.Unmarshal(w.Body.Bytes(), &response)
	assert.NoError(t, err)

	assert.Equal(t, "Order processed successfully", response["message"])
	
	orderRes := response["order"].(map[string]interface{})
	assert.Equal(t, float64(10), orderRes["id"])
	mockSvc.AssertExpectations(t)
}

func TestHandleProcessOrder_InvalidJSON(t *testing.T) {
	mockSvc := new(MockOrderService)
	router := setupRouter(mockSvc)

	invalidJSON := []byte(`{"customer_id": "text_instead_of_int"}`)

	req, _ := http.NewRequest(http.MethodPost, "/api/orders", bytes.NewBuffer(invalidJSON))
	req.Header.Set("Content-Type", "application/json")

	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusBadRequest, w.Code)
	assert.Contains(t, w.Body.String(), "Invalid JSON format")
}

func TestHandleProcessOrder_ServiceError(t *testing.T) {
	mockSvc := new(MockOrderService)
	router := setupRouter(mockSvc)

	reqPayload := service.ProcessOrderRequest{
		CustomerID: 1,
		StoreID:    1,
		Amount:     -100.0,
	}
	body, _ := json.Marshal(reqPayload)

	mockSvc.On("ProcessOrder", reqPayload).Return((*models.Order)(nil), errors.New("invalid order amount"))

	req, _ := http.NewRequest(http.MethodPost, "/api/orders", bytes.NewBuffer(body))
	req.Header.Set("Content-Type", "application/json")

	w := httptest.NewRecorder()
	router.ServeHTTP(w, req)

	assert.Equal(t, http.StatusInternalServerError, w.Code)
	assert.Contains(t, w.Body.String(), "invalid order amount")
	mockSvc.AssertExpectations(t)
}
